### ISSUE TITLE
QuickFF 2.2.5 + Yaff 1.6.0

### ISSUE THREAD

**Issue by SanderBorgmans** [molmod/QuickFF#15]
It seems the latest versions of Yaff (1.6.0) and QuickFF (2.2.5) are no longer compatible (at least on my own workstation). Executing the qff.py program returns the following traceback:

```
Traceback (most recent call last):
  File "/home/sander/.local/bin/qff.py", line 38, in <module>
    qff()
  File "/home/sander/.local/lib/python3.6/site-packages/quickff/scripts.py", line 447, in qff
    program.run()
  File "/home/sander/.local/lib/python3.6/site-packages/quickff/program.py", line 701, in run
    self.do_pt_generate()
  File "/home/sander/.local/lib/python3.6/site-packages/quickff/program.py", line 283, in do_pt_generate
    pickle.dump(self.trajectories, open(fn_traj, 'wb'))
  File "stringsource", line 2, in yaff.pes.ext.Cell.__reduce_cython__
TypeError: no default __reduce__ due to non-trivial __cinit__
```
Downgrading Yaff to 1.5.0 fixes this issue.

**Comment by SanderBorgmans** [comment]
Has this been looked into?
